### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by HttpAnimation** [HelgeSverre/ollama-gui#15]
```
httpanimations@debian:~/ollama-gui$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
httpanimations@debian:~/ollama-gui$ ls
```

**Comment by HelgeSverre** [comment]
You need [yarn](https://yarnpkg.com/) installed

**Comment by HttpAnimation** [comment]
I do
httpanimations@debian:~$ yarn --version
0.32+git
httpanimations@debian:~$

**Comment by BoredManCodes** [comment]
For future people:
```sh
sudo apt remove cmdtest
sudo apt remove yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update
sudo apt-get install yarn -y
```

**Comment by HelgeSverre** [comment]
just a note for others.

You can use NPM instead of Yarn by using `npm install`, practically it will make no difference at all.

I prefer Yarn, because it is easier to type fast, has a progress bar when it installs things, and I have used it for years, there is no other reason this project uses Yarn instead of NPM.
